# Generated by Django 5.0.6 on 2024-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_class_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
