# Generated by Django 5.0.4 on 2024-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
