# Generated by Django 5.0.4 on 2024-06-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_teacher_profile_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
