# Generated by Django 5.0.4 on 2024-06-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
