# Generated by Django 5.0.4 on 2024-06-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_grade_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='semester',
        ),
    ]
