# Generated by Django 5.0.4 on 2024-06-18 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_grade_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
    ]
